jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      id: docker_build
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: ./
        file: ./Dockerfile
        push: false
        tags: erudikaltd/scoold:latest
    - continue-on-error: true
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    - continue-on-error: true
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: '${{ runner.os }}-buildx-

          '
name: Docker Hub - latest
on:
  repository_dispatch:
    types: trigger-ga___latest.yml
